### ISSUE TITLE
Array conversion bug in make_form

### ISSUE THREAD

**Issue by Willaem** [catalystneuro/json-schema-to-dash-forms#11]
Greetings!

I'm trying to use the nwb-web-gui to convert data into nwb, but I keep getting the same bug in the make_form function. Traceback is as such :
```python
Traceback (most recent call last):
  File "/home/willaem/PycharmProjects/nwb-ui-converter/src/nwbuiconverter/gui/ncGui.py", line 27, in <module>
    app = init_app()
  File "/home/willaem/.local/lib/python3.8/site-packages/nwb_web_gui/__init__.py", line 41, in init_app
    converter = init_converter(server=app, converter_class=converter_class)
  File "/home/willaem/.local/lib/python3.8/site-packages/nwb_web_gui/dashapps/pages/converter/init_coverter.py", line 29, in init_converter
    ConverterForms(parent_app=dash_app, converter_class=converter_class)
  File "/home/willaem/.local/lib/python3.8/site-packages/nwb_web_gui/dashapps/pages/converter/converter.py", line 50, in __init__
    self.source_forms = SchemaFormContainer(
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 392, in __init__
    self.construct_children_forms()
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 665, in construct_children_forms
    iform = SchemaForm(
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 282, in __init__
    self.make_form(properties=schema['properties'])
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 328, in make_form
    elif isinstance(v['items'], dict):
KeyError: 'items'
```
I was able to fix the issue by changing the line 328 of `forms.py` to this :
```python
elif 'items' in v and isinstance(v['items'], dict):
```
This seemed to prevent the KeyError thrown. Do you have any idea what is happening there? Thanks!

**Comment by luiztauffer** [comment]
Hey @Willaem , this does sound like something that should be safely tested the way you did, thanks for reporting that!
But at the same time, we should make sure it is not an invalid schema being passed. Which converter you are using when getting this error?

**Comment by Willaem** [comment]
I am using a very simple custom converter based on the tiffDataInterface as presented here :
```python
class exempleImageConverter(NWBConverter):
    data_interface_classes = dict(
        TiffImaging=TiffImagingInterface
    )
```

**Comment by luiztauffer** [comment]
@Willaem oh right, the Ophys datainterfaces were not thoroughly tested with the GUI, which requires some specific configurations for the schemas produced. I will check this next week and inform you when the problem is solved

**Comment by Willaem** [comment]
Thanks a lot!
In that case, the other bug I met (that I reported on the nwb-web-gui github page) might also come from this as well. Should I repost it in json-schema-to-dash-forms? You might meet that bug too very soon.

[Link to the issue in question](https://github.com/catalystneuro/nwb-web-gui/issues/51)
