### ISSUE TITLE
path finding error

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/json-schema-to-dash-forms#8]
```
(base) Bens-MacBook-Pro-2:nwb-conversion-tools bendichter$ metadata-gui --data_path "." --dev True
Metadata editing GUI running on localhost:5000
Data path: .
Running in development mode
Traceback (most recent call last):
  File "/Users/bendichter/opt/anaconda3/bin/metadata-gui", line 10, in <module>
    sys.exit(cmd_line_shortcut())
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/heidelberg_metadata_gui/cmd_line.py", line 49, in cmd_line_shortcut
    app = init_app()
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/heidelberg_metadata_gui/__init__.py", line 30, in init_app
    init_forms(server=app, converter_class=converter_class)
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/heidelberg_metadata_gui/metadata_forms/init_forms.py", line 23, in init_forms
    MetadataForms(parent_app=dash_app, converter_class=converter_class)
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/heidelberg_metadata_gui/metadata_forms/metadata_forms.py", line 43, in __init__
    parent_app=self.parent_app
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 370, in __init__
    self.construct_children_forms()
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 603, in construct_children_forms
    container=self
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 282, in __init__
    self.make_form(properties=schema['properties'])
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 335, in make_form
    required=required
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 23, in __init__
    field_input = self.get_field_input(value=value, input_id=input_id, required=required)
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/forms.py", line 131, in get_field_input
    display=value['format']
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/utils.py", line 17, in make_filebrowser_modal
    display=display
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/utils.py", line 50, in __init__
    self.make_dict_from_dir(display=display)
  File "/Users/bendichter/opt/anaconda3/lib/python3.7/site-packages/json_schema_to_dash_forms/utils.py", line 154, in make_dict_from_dir
    splitted = e['key'].split(splitter, maxsplit=1)[1]
ValueError: empty separator
```

**Comment by vinicvaz** [comment]
I can't reproduce it. 
have you uninstalled and reinstalled the json-schema-form?
